package Recetas;

import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author santi-juli
 */
public class Postres extends javax.swing.JPanel {

    /**
     * Creates new form Postres
     */
    public Postres() {
        initComponents();
        ingredientes.setLineWrap(true);
        ingredientes.setWrapStyleWord(true);
        ingredientes.setVisible(false);
        pasos.setLineWrap(true);
        pasos.setWrapStyleWord(true);
        pasos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mousse = new javax.swing.JButton();
        fresas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        imagen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ingredientes = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        pasos = new javax.swing.JTextArea();
        atras = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Postres");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Fresas con crema");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mousse Maracuya");

        mousse.setText("Seleccionar");
        mousse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mousseActionPerformed(evt);
            }
        });

        fresas.setText("Seleccionar");
        fresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fresasActionPerformed(evt);
            }
        });

        ingredientes.setColumns(20);
        ingredientes.setRows(5);
        jScrollPane1.setViewportView(ingredientes);

        pasos.setColumns(20);
        pasos.setRows(5);
        jScrollPane2.setViewportView(pasos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(imagen)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(imagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        atras.setText("Atras");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(fresas)
                        .addGap(100, 100, 100)
                        .addComponent(atras))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(mousse)))
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fresas)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(mousse)
                        .addComponent(atras)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    String rutaArchivo = "C:\\Users\\Cristian\\OneDrive\\Documentos\\Universidad\\POO\\book\\BooksRecipe\\textosRecetas\\"; // Reemplaza con la ruta de tu archivo

    private void fresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fresasActionPerformed
        ImageIcon imagenIcono = new ImageIcon("C:\\Users\\Cristian\\OneDrive\\Documentos\\Universidad\\POO\\book\\BooksRecipe\\images\\fresas.jpg"); // Reemplaza con la ruta de tu imagen
        
        Image imagenOriginal = imagenIcono.getImage();
        Image imagenRedimensionada = imagenOriginal.getScaledInstance(500, 250, Image.SCALE_SMOOTH);
        
        ImageIcon imagenRedimensionadaIcono = new ImageIcon(imagenRedimensionada);
        imagen.setIcon(imagenRedimensionadaIcono);
        
        ingredientes.setVisible(true);
        pasos.setVisible(true);
        try {
            File archivo1 = new File(rutaArchivo + "fresasIng.txt");
            File archivo2 = new File(rutaArchivo + "fresasPre.txt");
            FileReader fileReader1 = new FileReader(archivo1);
            FileReader fileReader2 = new FileReader(archivo2);
            BufferedReader bufferedReader1 = new BufferedReader(fileReader1);
            BufferedReader bufferedReader2 = new BufferedReader(fileReader2);
            
            String linea;
            ingredientes.setText("");
            pasos.setText("");
            while ((linea = bufferedReader1.readLine()) != null) {
                String currText = ingredientes.getText() + "\n";
                String nextText = currText + linea;
                ingredientes.setText(nextText);
            }    
            while ((linea = bufferedReader2.readLine()) != null) {
                String currText = pasos.getText() + "\n";
                String nextText = currText + linea;
                pasos.setText(nextText);
            }
            
            bufferedReader1.close();
            bufferedReader2.close();
        } catch (IOException e) {
            System.out.println("Error al leer el archivo: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_fresasActionPerformed

    private void mousseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mousseActionPerformed
        ImageIcon imagenIcono = new ImageIcon("C:\\Users\\Cristian\\OneDrive\\Documentos\\Universidad\\POO\\book\\BooksRecipe\\images\\mousse.jpg"); // Reemplaza con la ruta de tu imagen
        
        Image imagenOriginal = imagenIcono.getImage();
        Image imagenRedimensionada = imagenOriginal.getScaledInstance(500, 250, Image.SCALE_SMOOTH);
        
        ImageIcon imagenRedimensionadaIcono = new ImageIcon(imagenRedimensionada);
        imagen.setIcon(imagenRedimensionadaIcono);
        
        ingredientes.setVisible(true);
        pasos.setVisible(true);
        try {
            File archivo1 = new File(rutaArchivo + "mushIng.txt");
            File archivo2 = new File(rutaArchivo + "mushPre.txt");
            FileReader fileReader1 = new FileReader(archivo1);
            FileReader fileReader2 = new FileReader(archivo2);
            BufferedReader bufferedReader1 = new BufferedReader(fileReader1);
            BufferedReader bufferedReader2 = new BufferedReader(fileReader2);
            
            String linea;
            ingredientes.setText("");
            pasos.setText("");
            while ((linea = bufferedReader1.readLine()) != null) {
                String currText = ingredientes.getText() + "\n";
                String nextText = currText + linea;
                ingredientes.setText(nextText);
            }    
            while ((linea = bufferedReader2.readLine()) != null) {
                String currText = pasos.getText() + "\n";
                String nextText = currText + linea;
                pasos.setText(nextText);
            }
            
            bufferedReader1.close();
            bufferedReader2.close();
        } catch (IOException e) {
            System.out.println("Error al leer el archivo: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_mousseActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        this.setVisible(false);
        menu m = new menu(1);
        m.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atras;
    private javax.swing.JButton fresas;
    private javax.swing.JLabel imagen;
    private javax.swing.JTextArea ingredientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton mousse;
    private javax.swing.JTextArea pasos;
    // End of variables declaration//GEN-END:variables
}
